Amendment
Kyle-Law/Youtube-Clone-Daniel-Kyle pull request #6
Opened 2020-01-14 12:25 UTC by Kyle-Law

Youtube Clone completed. It's responsive.
Live link deployed: https://rawcdn.githack.com/Kyle-Law/Youtube-Clone-Daniel-Kyle/b6fab969116a2aba4bb920a635bff3be94b29c02/index.html

2020-01-14 22:01 UTC, kobiyoyo commented
### Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-01-14 22:34 UTC, kobiyoyo requested changes
## Hi Team![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there few changes required. 

### Page structure
- [x] There must be a share button
- [x] It shows the avatar of the user who uploaded the video
- [x] It has a subscribe button
![1](https://user-images.githubusercontent.com/23278161/72388371-062b3000-3726-11ea-9cd6-8b5ba2cf189e.png)


### Make changes and submit another code review request.
*Happy coding*

2020-01-15 10:17 UTC, nikasulo requested changes
# This is amazing Work! 
One tiny issue, your stickler errors persist. Please fix all errors and request another review. I wish you the best 😊.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-01-15 13:09 UTC, Kyle-Law commented on styles.css
> +    grid-template-columns: repeat(2,1fr);
Tried but unable to resolve RBRACE error.

2020-01-15 13:09 UTC, Kyle-Law commented on styles.css
> +    grid: repeat(2,1fr) / 60px 1fr;
Tried but unable to resolve RBRACE error.

2020-01-15 13:09 UTC, Kyle-Law commented
Tried but unable to resolve RBRACE error. They are the last 2 lint errors that we can't resolve.

2020-01-15 15:37 UTC, simonpeterdebbarma commented
Hi guys,

Your .stickler.yml file is configured incorrectly. You have it configured for bower instead of stylelint.

```
linters:
  stylelint:
    config: 'stylelint.config.js'
```

2020-01-15 18:23 UTC, nikasulo approved these changes
# Fantastic work @Kyle-Law and @simonpeterdebbarma!
I saw your message on Twitter about needing some assistance, apologies for not responding on time, trying to meet up with the deadline for my final capstone project so I was off social media the whole day. However, I will send you my contact so you can reach me at anytime subsequently if you need assistance.

All that being said, this is awesome guys! You deserve nothing short of an approval! Please merge and move to exfil! Bravo-one out :rocket:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-01-15 22:49 UTC, simonpeterdebbarma commented
LMAO I wasn't part of this project. I'm a mentor of the other guy who worked on this, @Daniel. They had some stickler issue so I just dropped by to help.

2020-01-16 03:26 UTC, Kyle-Law commented
Thanks @simonpeterdebbarma for the helping hand! It's a lifesaver.
Thanks @Oluwadamilareolusakin for reviewing our project 👍  Good luck to your capstone!

2020-01-16 03:27 UTC, merged